In [1]:
import numpy as np

## Linear Algebra
- Vectors and Matrices
- concerns itself with linear systems but represents them through vectors and matrices

**Vector**
- simply put: arrow in space with specific direction and length
- often represents a piece of data
- central building block of linear algebra

In [4]:
# example vector
v = [3,2]
print(v)

[3, 2]


- in practice one would rather use numpy to work with vectors than plane python

In [3]:
# using numpy
v = np.array([3,2])
print(v)

[3 2]


- vectors have many practical applications
- physics: direction and magnitude
- math: direction and scale on XY plane
- computer and data science: Array of numbers storing data

In [7]:
# 3 dimensional vector
v = np.array([3,5,2])
print(v)

#5 dimensional vector
v = np.array([1,4,3,6,8])
print(v)

[3 5 2]
[1 4 3 6 8]


**Adding Vectors**
- add or substract each x or y (or more) values
- graphical meaning: v1 starts at (0,0). at end of v1 add v2 (so it starts at end of v1 not 0,0). Then draw line from (0,0) to end of v2. this is the rsulting vector of v1 + v2
- order of operation does not matter. v1 + v2 = v2 + v1

In [9]:
v1 = np.array([3,5])
v2 = np.array([-2, 6])
print(v1 + v2)

[ 1 11]


**Scaling Vectors**
- scaling = growing or shrinking a vectors length
- by multiplication with a scalar (single value)
- you multiply each value of the vector by the scalar

In [11]:
v = np.array([2,3])
s = 2
print(v*s)

[4 6]


**Span**
- through adding and scalling two vectors, you can create any other vector
- the space of possible vectors is called span
- usually span can create an unlimited amount of resulting vectors

**Linear independent vectors**
- vectors that have different direction are linear independent
- they have unlimited span

**Linear dependent vectors**
- vectors have same direction
- span is limited to be on that same direction
- impossible to create any new vectors by scaling
- in 3 or more dimensions, when all vectors are linearly dependent, they are usually stuck on a less dimensional plane
- ie 2d plane instead of 3d

**Why linearly independent vs dependent**
- a lot of problems become difficult or unsolvable when vectors are linearly dependent
- for example linearly dependent set of equations can become impossible to solve

**Linear transformation**
- use of vectors to change other vector, through adding  scaling etc

**Basis Vector**
- are used as a set of vectors to transform other vectors
- usually have length 1 and point in perpendicular positive direction
- basis vector = ([i][j]) = ([1,0][0,1])
- we can create any vector we want by scaling and adding the two vectors

**Linear transformation Movements**
- scale: stretching or shortening the 
- rotation: flip sign, so point vector in other direction
- inversion: flip the columns, so i and j swap 
- shear: same as scaling, but using value from other row. ie prolonging along the x axis not y axis
- cant have transformations that are non-linear and result in curves etc

**Matrix vector multiplication**
- ([1,2][3,4]) * [x,y] = [1*x + 3y, 2*x + 4y]
- is called dot product

In [14]:
# create basic matrix
basic = np.array([[3,0],[0,2]])
print(basic)

# create vector to multiply it
v = np.array([1,1])
print(v)

# create new vector by using dot product
print(basic.dot(v))

[[3 0]
 [0 2]]
[1 1]
[3 2]


In [19]:
# author prefers creating basis vectors independently and putting them into a matrix then
# need to use transpose because numpy will do it the wrong way

i_hat = np.array([3,0])
j_hat = np.array([0,2])
print(i_hat, j_hat)

basis = np.array([i_hat, j_hat]).transpose()
print(basis)

v = np.array([1,1])
print(v)

print(basis.dot(v))

[3 0] [0 2]
[[3 0]
 [0 2]]
[1 1]
[3 2]


**Basis vectors in 3d and more**
- you just use more basis vactors, ie i,j,k and more

**Matrix Multiplication**
- matrix multiplication adds multiple transformations to the vector space
- for example, you could add a rotation and then a shear to a vector
- in this case you would first multiply the rotation matrix and the shear matrix
- and then multiply hte resulting matrix with the vector
- example below: using np.transpose() so np stores array in desired shape
- multiplication order matters!

In [30]:
# rotation matrix
r = np.transpose(np.array([[0,1],[-1,0]]))
print(r)

# shear matrix
sh = np.transpose(np.array([[1,0],[1,1]]))
print(sh)

# vector
v = np.array([1,2])
print(v)

# rotation * shear
r_sh = sh @ r
print(r_sh)

# result * v
print(r_sh.dot(v))

[[ 0 -1]
 [ 1  0]]
[[1 1]
 [0 1]]
[1 2]
[[ 1 -1]
 [ 1  0]]
[-1  1]


**Determinants**
- determinant is the area covered by a matrix
- is calculated using the matrix values
- identity matrix has determinant 1

In [4]:
# calculating determinant

basis = np.transpose(np.array([[3,0],[0,2]]))

determinant = np.linalg.det(basis)

print(determinant)

6.0


- scaling will increase or decrease the determinant
- flipping will flip its sign
- if det = 0 then matrix is linearly dependent

**Special Types of matrices**
- square matrix: equal number rows and columns. Are requirement for many operations
- identity matrix: square matrix with diagonal of 1s while other values are 0s. Consists of basis vectors after undoing all transformations
- Inverse matrix: Undoes transformation on another matrix. So Inverse * Matrix = Identity matrix. Inverse notation: m**-1
- diagonal matrix: like identity matrix, but diagonal can be any values shile rest is 0s
- triangular matrix: diagonal and above are non 0, below diagonal are 0s (or opposite). Easy to solve
- sparse matrix: Matrix that is mostly 0s. 

**Systems of Equations and Inverse Matrices**
- solving systems of equations is one of linear algebras basic use cases
- systems of equations can be formulated as matrix operations
- then we can use inverse to undo the transformations on the matrix and receive the values of the variables
- example below:

In [8]:
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = np.array([[4, 2, 4],[5, 3, 7],[9, 3, 6]])

B = np.array([44, 56, 72])

X = np.linalg.inv(A).dot(B)

print(A)
print(B)
print(np.linalg.inv(A))
print(X)

# solution: x = 2, y = 34, z = -8

[[4 2 4]
 [5 3 7]
 [9 3 6]]
[44 56 72]
[[-5.00000000e-01  9.86864911e-17  3.33333333e-01]
 [ 5.50000000e+00 -2.00000000e+00 -1.33333333e+00]
 [-2.00000000e+00  1.00000000e+00  3.33333333e-01]]
[ 2. 34. -8.]


**Linear Programming**
- solves system of inequalities
- integer programming: only integers
- mixed integer programming: floats and integers
- example:
- 2 product lines, ipac and ipac ultra
- ipac makes 200 profit, ipac ultra makes 300 profit
- assembly line can work 20 hours and Ipac takes 1 hour and ipac ultra takes 3 hours
- 45 kits can be provided in a day and ipac needs 6 kits while ipac ultra requires 2 kits
- assuming all supply will be sold, how much of each should be produced to maximize profit?
- Solution:

In [8]:
from pulp import *

# lpvariable declares variables to solve for
x = LpVariable("x", 0, cat = LpInteger) # x >= 0 & x has to be an integer, cant be a float
y = LpVariable("y", 0, cat = LpInteger) # y >= 0 & y has to be integer no float

# LpProblem defines the problem
prob = LpProblem("factory_problem", LpMaximize)

# define constraints (i think these are added to the prob)
prob += x + 3*y <= 20
prob += 6*x + 2*y <= 45

# defines objective function to maximize
prob += 200*x + 300*y

# solve the problem
status = prob.solve()
print("x = ", value(x), " y = ", value(y))

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/marklakshman/Coding_Projects/Math for DS testing/venv/lib/python3.9/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/s7/ckxkrdg10w99sm10_yhbwr7c0000gn/T/cc9500a7e25e40ed98045fe20bcbd359-pulp.mps max timeMode elapsed branch printingOptions all solution /var/folders/s7/ckxkrdg10w99sm10_yhbwr7c0000gn/T/cc9500a7e25e40ed98045fe20bcbd359-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 18 RHS
At line 21 BOUNDS
At line 24 ENDATA
Problem MODEL has 2 rows, 2 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2593.75 - 0.00 seconds
Cgl0004I processed model has 2 rows, 2 columns (2 integer (0 of which binary)) and 4 elements
Cutoff increment increased from 1e-05 to 99.9999
Cbc0012I Integer solution of -2200 found by DiveCoefficient after 0 iterations and 0 no

**Matrix decomposition**
- breaking up matrix into basic components
- common method for matrix decomposition: Eigendecomposition
- is used to break up matrix into components that are easier to work with in different machine learning tasks
- only works on square matrices
- 2 components: Eigenvalues lambda and Eigenvector v
- for Matrix A: A*v = lambda*v
- for each dimension of the matrix (ie for ech column) there is one eigenvalue and one eigenvector

In [12]:
# calculating eigenvectors and eigenvalues

A = np.array([[1,2,3],[4,5,6], [7,8,9]])

eigenvals, eigenvecs = np.linalg.eig(A)

print(eigenvals)
print(eigenvecs)

[ 1.61168440e+01 -1.11684397e+00 -8.58274334e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


**Rebuilding Matrix after decomposition**
- A = Eigenvectors * Eigenvalues in Matrix form * inv(Eigenvectors)
- A = Q * L (Eigenvectors in matrix form (diagonal matrix)) * R (inv(Q))

In [14]:
# reconstructing matrix after decomposition above
Q = eigenvecs
R = np.linalg.inv(Q)
L = np.diag(eigenvals)

B = Q @ L @ R
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Exercises

**1)**
- v [1,2]
- transformation: i [2,0], j[0, 1.5]
- where does v land?

In [17]:
v = np.array([1,2])
i = np.array([2,0])
j = np.array([0, 1.5])

basis = np.array([i,j])
print(basis.dot(v))

[2. 3.]


**2)**

In [18]:
v = np.array([1,2])
i = np.array([-2,1])
j = np.array([1,-2])

basis = np.array([i,j])
print(basis.dot(v))

[ 0 -3]


**3)**


In [19]:
i = np.array([1,0])
j = np.array([2,2])
basis = np.array([i,j])

print(np.linalg.det(basis))

2.0


**5)**

In [21]:
# 3x + 1y + 0z = 54
# 2x + 4y + 1z = 12
# 3x + 1y+ 8z = 6

A = np.array([[3,1,0],[2,4,1],[3,1,8]])
x = np.array([54,12,6])

# spelled out: A*(x,y,z) = x
# to eliminate A: multiply with A**(-1) and only (x,y,z) will remain on left side
# we have to do same operation on right side so A**(-1) * x

print(np.linalg.inv(A).dot(x))

[19.8 -5.4 -6. ]


**6)**

In [22]:
# following matrix linearly dependent? (is determinant = 0)?

A = np.array([[2,6],[1,3]])

print(np.linalg.det(A))

0.0
