In [2]:
import numpy as np

## Linear Algebra
- Vectors and Matrices
- concerns itself with linear systems but represents them through vectors and matrices

**Vector**
- simply put: arrow in space with specific direction and length
- often represents a piece of data
- central building block of linear algebra

In [4]:
# example vector
v = [3,2]
print(v)

[3, 2]


- in practice one would rather use numpy to work with vectors than plane python

In [3]:
# using numpy
v = np.array([3,2])
print(v)

[3 2]


- vectors have many practical applications
- physics: direction and magnitude
- math: direction and scale on XY plane
- computer and data science: Array of numbers storing data

In [7]:
# 3 dimensional vector
v = np.array([3,5,2])
print(v)

#5 dimensional vector
v = np.array([1,4,3,6,8])
print(v)

[3 5 2]
[1 4 3 6 8]


**Adding Vectors**
- add or substract each x or y (or more) values
- graphical meaning: v1 starts at (0,0). at end of v1 add v2 (so it starts at end of v1 not 0,0). Then draw line from (0,0) to end of v2. this is the rsulting vector of v1 + v2
- order of operation does not matter. v1 + v2 = v2 + v1

In [9]:
v1 = np.array([3,5])
v2 = np.array([-2, 6])
print(v1 + v2)

[ 1 11]


**Scaling Vectors**
- scaling = growing or shrinking a vectors length
- by multiplication with a scalar (single value)
- you multiply each value of the vector by the scalar

In [11]:
v = np.array([2,3])
s = 2
print(v*s)

[4 6]


**Span**
- through adding and scalling two vectors, you can create any other vector
- the space of possible vectors is called span
- usually span can create an unlimited amount of resulting vectors

**Linear independent vectors**
- vectors that have different direction are linear independent
- they have unlimited span

**Linear dependent vectors**
- vectors have same direction
- span is limited to be on that same direction
- impossible to create any new vectors by scaling
- in 3 or more dimensions, when all vectors are linearly dependent, they are usually stuck on a less dimensional plane
- ie 2d plane instead of 3d

**Why linearly independent vs dependent**
- a lot of problems become difficult or unsolvable when vectors are linearly dependent
- for example linearly dependent set of equations can become impossible to solve

**Linear transformation**
- use of vectors to change other vector, through adding  scaling etc

**Basis Vector**
- are used as a set of vectors to transform other vectors
- usually have length 1 and point in perpendicular positive direction
- basis vector = ([i][j]) = ([1,0][0,1])
- we can create any vector we want by scaling and adding the two vectors

**Linear transformation Movements**
- scale: stretching or shortening the 
- rotation: flip sign, so point vector in other direction
- inversion: flip the columns, so i and j swap 
- shear: same as scaling, but using value from other row. ie prolonging along the x axis not y axis
- cant have transformations that are non-linear and result in curves etc

**Matrix vector multiplication**
- ([1,2][3,4]) * [x,y] = [1*x + 3y, 2*x + 4y]
- is called dot product

In [14]:
# create basic matrix
basic = np.array([[3,0],[0,2]])
print(basic)

# create vector to multiply it
v = np.array([1,1])
print(v)

# create new vector by using dot product
print(basic.dot(v))

[[3 0]
 [0 2]]
[1 1]
[3 2]


In [19]:
# author prefers creating basis vectors independently and putting them into a matrix then
# need to use transpose because numpy will do it the wrong way

i_hat = np.array([3,0])
j_hat = np.array([0,2])
print(i_hat, j_hat)

basis = np.array([i_hat, j_hat]).transpose()
print(basis)

v = np.array([1,1])
print(v)

print(basis.dot(v))

[3 0] [0 2]
[[3 0]
 [0 2]]
[1 1]
[3 2]


**Basis vectors in 3d and more**
- you just use more basis vactors, ie i,j,k and more

**Matrix Multiplication**
- matrix multiplication adds multiple transformations to the vector space
- for example, you could add a rotation and then a shear to a vector
- in this case you would first multiply the rotation matrix and the shear matrix
- and then multiply hte resulting matrix with the vector
- example below: using np.transpose() so np stores array in desired shape
- multiplication order matters!

In [30]:
# rotation matrix
r = np.transpose(np.array([[0,1],[-1,0]]))
print(r)

# shear matrix
sh = np.transpose(np.array([[1,0],[1,1]]))
print(sh)

# vector
v = np.array([1,2])
print(v)

# rotation * shear
r_sh = sh @ r
print(r_sh)

# result * v
print(r_sh.dot(v))

[[ 0 -1]
 [ 1  0]]
[[1 1]
 [0 1]]
[1 2]
[[ 1 -1]
 [ 1  0]]
[-1  1]
